/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Customer: typeof import('./src/components/customer.vue')['default']
    Echart: typeof import('./src/components/Echart/src/Echart.vue')['default']
    Invest: typeof import('./src/components/invest.vue')['default']
    Mine: typeof import('./src/components/mine.vue')['default']
    Performance: typeof import('./src/components/performance.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
