/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BasicProductCardList: typeof import('./../components/product/basic-product-card-list.vue')['default']
    Card: typeof import('./../components/Card/src/Card.vue')['default']
    CartTitle: typeof import('./../components/Card/src/CartTitle.vue')['default']
    Echart: typeof import('./../components/Echart/src/Echart.vue')['default']
    MyUploader: typeof import('./../components/upload/my-uploader.vue')['default']
    OrderBottom: typeof import('./../components/delivery/order-bottom.vue')['default']
    OrderMainInfo: typeof import('./../components/delivery/order-main-info.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StoreAndDateSelect: typeof import('./../components/storeAndDateSelect.vue')['default']
    StoreSelect: typeof import('./../components/store-select.vue')['default']
    Tabbar: typeof import('./../components/tabbar.vue')['default']
  }
}
